//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymbolDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParseErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParseErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SymbolDecoder.ParseErrors", typeof(ParseErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid symbol names start with &apos;?&apos;, not &apos;{0}&apos;.
        /// </summary>
        public static string BadSymbolStart {
            get {
                return ResourceManager.GetString("BadSymbolStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-reference type.
        /// </summary>
        public static string DoubleReference {
            get {
                return ResourceManager.GetString("DoubleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name fragments cannot empty.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected at least one parameter type for function.
        /// </summary>
        public static string EmptyParameterList {
            get {
                return ResourceManager.GetString("EmptyParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected function return type.
        /// </summary>
        public static string ExpectedReturnType {
            get {
                return ResourceManager.GetString("ExpectedReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected template name.
        /// </summary>
        public static string ExpectedTemplateName {
            get {
                return ResourceManager.GetString("ExpectedTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid back reference {0}.
        /// </summary>
        public static string InvalidBackRef {
            get {
                return ResourceManager.GetString("InvalidBackRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid __based pointer code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidBasedPointerType {
            get {
                return ResourceManager.GetString("InvalidBasedPointerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function call convention code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCallingConvention {
            get {
                return ResourceManager.GetString("InvalidCallingConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character encountered in symbol &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data symbol code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidDataEncoding {
            get {
                return ResourceManager.GetString("InvalidDataEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in integer encoding:&apos;{0}&apos;.
        /// </summary>
        public static string InvalidDimension {
            get {
                return ResourceManager.GetString("InvalidDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum base type code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidEnumType {
            get {
                return ResourceManager.GetString("InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extended type code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidExtendedTypeCode {
            get {
                return ResourceManager.GetString("InvalidExtendedTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function class code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidFunctionClass {
            get {
                return ResourceManager.GetString("InvalidFunctionClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function storage code {0}.
        /// </summary>
        public static string InvalidFunctionStorage {
            get {
                return ResourceManager.GetString("InvalidFunctionStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in identifier &apos;{0}&apos;.
        /// </summary>
        public static string InvalidIdentifierChar {
            get {
                return ResourceManager.GetString("InvalidIdentifierChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RTTI code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidRttiCode {
            get {
                return ResourceManager.GetString("InvalidRttiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid special name code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidSpecialNameCode {
            get {
                return ResourceManager.GetString("InvalidSpecialNameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid storage class code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidStorageClass {
            get {
                return ResourceManager.GetString("InvalidStorageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer storage modifiers can only be applied to pointers.
        /// </summary>
        public static string InvalidStorageModifierForNonPointer {
            get {
                return ResourceManager.GetString("InvalidStorageModifierForNonPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid symbol type &apos;{0}&apos;.
        /// </summary>
        public static string InvalidSymbolTypeCode {
            get {
                return ResourceManager.GetString("InvalidSymbolTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template argument code:&apos;{0}&apos;.
        /// </summary>
        public static string InvalidTemplateArgument {
            get {
                return ResourceManager.GetString("InvalidTemplateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template constant argument code:&apos;{0}&apos;.
        /// </summary>
        public static string InvalidTemplateConst {
            get {
                return ResourceManager.GetString("InvalidTemplateConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type code &apos;{0}&apos;.
        /// </summary>
        public static string InvalidTypeEncoding {
            get {
                return ResourceManager.GetString("InvalidTypeEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraneous characters encountered after decoded symbol.
        /// </summary>
        public static string NonsenseAtEndOfSymbol {
            get {
                return ResourceManager.GetString("NonsenseAtEndOfSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of the symbol was encountered before decoding was complete.
        /// </summary>
        public static string PrematureEndOfSymbol {
            get {
                return ResourceManager.GetString("PrematureEndOfSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Symbol: {0}
        ///{1} @ {2}.
        /// </summary>
        public static string SymbolParseErrorFormat {
            get {
                return ResourceManager.GetString("SymbolParseErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode truncated symbol.
        /// </summary>
        public static string TruncatedSymbol {
            get {
                return ResourceManager.GetString("TruncatedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;.
        /// </summary>
        public static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface qualifer type &apos;{0}&apos; is not implemented yet.
        /// </summary>
        public static string UnimplementedInterfaceQualifier {
            get {
                return ResourceManager.GetString("UnimplementedInterfaceQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated function symbol; expecting &apos;Z&apos;.
        /// </summary>
        public static string UnterminatedFunction {
            get {
                return ResourceManager.GetString("UnterminatedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated identifier; expected &apos;@&apos;.
        /// </summary>
        public static string UnterminatedName {
            get {
                return ResourceManager.GetString("UnterminatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated function parameter list; expected &apos;@&apos;, &apos;X&apos; or &apos;Z&apos;.
        /// </summary>
        public static string UnterminatedParameterList {
            get {
                return ResourceManager.GetString("UnterminatedParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated qualified name expected &apos;@&apos;.
        /// </summary>
        public static string UnterminatedQualifiedName {
            get {
                return ResourceManager.GetString("UnterminatedQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated template parameter list; expected &apos;@&apos;.
        /// </summary>
        public static string UnterminatedTemplateParameterList {
            get {
                return ResourceManager.GetString("UnterminatedTemplateParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused extended type code &apos;{0}&apos;.
        /// </summary>
        public static string UnusedExtendedTypeCode {
            get {
                return ResourceManager.GetString("UnusedExtendedTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused type code &apos;{0}&apos;.
        /// </summary>
        public static string UnusedTypeCode {
            get {
                return ResourceManager.GetString("UnusedTypeCode", resourceCulture);
            }
        }
    }
}
